# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
- R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
- mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
- mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot

install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'

before_script:
- R -q -e 'tic::before_script()'
- travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;" -uroot
- travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
- travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot

script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
cache: packages
latex: false
fortran: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#addons
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libmagick++-dev
    - libssh2-1-dev

matrix:
  include:
  - os: linux
    r: release
    env:
    - BUILD_PKGDOWN=true
  - os: linux
    r: devel
  - os: linux
    r: oldrel
  - os: linux
    r: 3.2
  - os: osx
    osx_image: xcode9.2
    before_install:
      - brew install mysql
      - mysql.server start
      - R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
      - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
      - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot
  - os: osx
    osx_image: xcode8.3
    disable_homebrew: true
    r_check_args: '--no-tests'
    before_script: 'echo no sql server, only testing build'
  - os: osx
    osx_image: xcode7.3
    disable_homebrew: true
    r_check_args: '--no-tests'
    before_script: 'echo no sql server, only testing build'

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

# Custom parts:

#services
services:
- MySQL
